# This is a YAML file that contains the configuration for paths, filenames and other settings.

path:
  raw_data: "../../data/raw/eICU"
  original_cohorts: "../../data/cohorts/sepsis_eicu_robin"
  cohorts: "../../data/cohorts/sepsis_eicu_extended"
  interim: "../../data/interim"
  features: "../../data/processed"
  results: "../../results"

filename:
  raw_patient_data: "patient.csv"
  static_data: "sta.parquet"
  dynamic_data: "dyn.parquet"
  outcome_data: "out.parquet"
  combined: "combined.parquet"
  features: "features.parquet"

config_settings:
  random_split_reps: 5 # Number of repetitions for each performed random split of the data
  test_size: 0.2 # Test size for the train-test split
  feature_extraction_columns_to_exclude: ["stay_id", "time", "age", "sex", "height", "weight", "label", "ethnicity", "hospitalid", "unittype", "hospitaladmitoffset", "uniquepid"]
  training_columns_to_drop: ["label", "hospitalid", "stay_id", "uniquepid"] # Columns to drop during training (X_train, X_test)